###
POST http://localhost:3000/groups
Content-Type: application/json

{
  "name": "운동",
  "description": "운동할 사람",
  "photo": "",
  "goalRep": 1000,
  "discordURL": "어래ㅔ너ㅡ르",
  "invitationURL": "fjldmfo",
  "tags": ["#안녕", "운동"],
  "ownerNickName": "운린이",
  "ownerPassword": "123456"
}


###
GET http://localhost:3000/groups

###
GET http://localhost:3000/groups/45ce7837-b487-4292-8353-f3ccb6f17853

###
POST http://localhost:3000/groups/26d20037-124a-4867-baa8-a8265b2f924f/likes

###
DELETE http://localhost:3000/groups/26d20037-124a-4867-baa8-a8265b2f924f/likes