### 운동기록 생성을 위한 스탑워치 시작
POST http://localhost:3000/groups/a8a9140e-c234-4722-9255-cb87ac3e5586/start
Content-Type: application/json


### 운동기록 생성
PATCH http://localhost:3000/groups/44d8b632-b157-441e-bf4f-f508bba08987/records
Content-Type: application/json

{
  "nickName": "testUser2",
  "password": "password123", 
  "sports": "SWIMMING",
  "description": "string",
  "photo": [
    "/uploads/1742177034230.png"],
  "distance": 0
}


### groupId에 속한 records 조회 
GET http://localhost:3000/groups/a8a9140e-c234-4722-9255-cb87ac3e5586/records

### groupId에 속한 records를 페이지네이션으로 조회
GET http://localhost:3000/groups/dec33a7c-b0df-447e-bd5c-aff2976df99d/records?offset=0&limit=3

### groupId에 속한 records를 오래된 순서로 조회
GET http://localhost:3000/groups/dec33a7c-b0df-447e-bd5c-aff2976df99d/records?order=oldest

### groupId에 속한 records를 최신순서로 조회
GET http://localhost:3000/groups/dec33a7c-b0df-447e-bd5c-aff2976df99d/records?order=newest

### groupId에 속한 records를 운동시간 내림차순으로 조회
GET http://localhost:3000/groups/dec33a7c-b0df-447e-bd5c-aff2976df99d/records?order=longtime

### groupId에 속한 records를 운동시간 오름차순으로 조회
GET http://localhost:3000/groups/dec33a7c-b0df-447e-bd5c-aff2976df99d/records?order=shorttime

### groupId에 속한 records를 닉네임으로 조회
GET http://localhost:3000/groups/dec33a7c-b0df-447e-bd5c-aff2976df99d/records?searchnickname=닉네임2


### 주간 랭킹 조회
GET http://localhost:3000/groups/dec33a7c-b0df-447e-bd5c-aff2976df99d/ranking/weekly

### 월간 랭킹 조회 
GET http://localhost:3000/groups/dec33a7c-b0df-447e-bd5c-aff2976df99d/ranking/monthly

### 멤버 참여 취소소
DELETE  http://localhost:3000/groups/0cefeff8-b2ff-4d57-a19d-e7c02e394688/members
Content-Type: application/json

{
  "nickName": "닉네임10",
  "password": "hello7!"
}

### 운동기록 목록조회
GET http://localhost:3000/groups/dec33a7c-b0df-447e-bd5c-aff2976df99d/records/4ca4d8c1-f41d-4394-898c-ed497c4a3fd0















###
GET http://localhost:3000/groups/0cefeff8-b2ff-4d57-a19d-e7c02e394688/ranking/weekly?page=2&limit=3

###

GET http://localhost:3000/groups/0cefeff8-b2ff-4d57-a19d-e7c02e394688/ranking/monthly

###
GET http://localhost:3000/groups/7632cbfe-a3f8-4195-b7d7-1a789bb5c281/records

### groupId에 속한 records 조회 
GET http://localhost:3000/groups/0cefeff8-b2ff-4d57-a19d-e7c02e394688/records

### groupId에 속한 records를 페이지네이션으로 조회
GET http://localhost:3000/groups/0cefeff8-b2ff-4d57-a19d-e7c02e394688/records?offset=0&limit=3

### groupId에 속한 records를 오래된 순서로 조회
GET http://localhost:3000/groups/0cefeff8-b2ff-4d57-a19d-e7c02e394688/records?order=oldest

### groupId에 속한 records를 최신순서로 조회
GET http://localhost:3000/groups/0cefeff8-b2ff-4d57-a19d-e7c02e394688/records?order=newest

### groupId에 속한 records를 운동시간 내림차순으로 조회
GET http://localhost:3000/groups/0cefeff8-b2ff-4d57-a19d-e7c02e394688/records?order=longtime

### groupId에 속한 records를 운동시간 오름차순으로 조회
GET http://localhost:3000/groups/0cefeff8-b2ff-4d57-a19d-e7c02e394688/records?order=shorttime

### groupId에 속한 records를 닉네임으로 조회
GET http://localhost:3000/groups/0cefeff8-b2ff-4d57-a19d-e7c02e394688/records?searchnickname=닉네임2

### 운동기록 생성을 위한 스탑워치 시작
POST http://localhost:3000/groups/start


### 운동기록 생성

POST http://localhost:3000/groups/0cefeff8-b2ff-4d57-a19d-e7c02e394688/records
Content-Type: application/json

{
  "sports": "SWIMMING",
  "description": "string",
  "distance": 20,
  "photo": [
    "https://example.com/cycling_group_photo.jpg"
  ],
  "nickName": "닉네임1",
  "password": "hello7!"
}


###
GET http://localhost:3000/groups/8dfe67ff-45a7-4bee-bd92-66bc9475361d/records/8d777393-a050-4828-9eea-7b2f4de3c7a5

###
GET http://localhost:3000/ranking/weekly

###
GET http://localhost:3000/groups/7632cbfe-a3f8-4195-b7d7-1a789bb5c281/records/4ca09a96-50af-44e8-ab8e-13e5b95ec444

