### groupId에 속한 records 조회 
GET http://localhost:3000/groups/b9878650-8432-47c7-b263-d4ffc8336c9f/records

### groupId에 속한 records를 페이지네이션으로 조회
GET http://localhost:3000/groups/b9878650-8432-47c7-b263-d4ffc8336c9f/records?offset=0&limit=3

### groupId에 속한 records를 오래된 순서로 조회
GET http://localhost:3000/groups/b9878650-8432-47c7-b263-d4ffc8336c9f/records?order=oldest

### groupId에 속한 records를 최신순서로 조회
GET http://localhost:3000/groups/b9878650-8432-47c7-b263-d4ffc8336c9f/records?order=newest

### groupId에 속한 records를 운동시간 내림차순으로 조회
GET http://localhost:3000/groups/b9878650-8432-47c7-b263-d4ffc8336c9f/records?order=longtime

### groupId에 속한 records를 운동시간 오름차순으로 조회
GET http://localhost:3000/groups/b9878650-8432-47c7-b263-d4ffc8336c9f/records?order=shorttime

### groupId에 속한 records를 닉네임으로 조회
GET http://localhost:3000/groups/b9878650-8432-47c7-b263-d4ffc8336c9f/records?searchnickname=닉네임2

### 운동기록 생성을 위한 스탑워치 시작
POST http://localhost:3000/groups/start

### 운동기록 생성
POST http://localhost:3000/groups/b9878650-8432-47c7-b263-d4ffc8336c9f/records
Content-Type: application/json

{
  "sports": "SWIMMING",
  "description": "string",
  "time": "21", 
  "distance": 20,
  "photo": [
    "https://example.com/cycling_group_photo.jpg"
  ],
  "nickName": "닉네임5",
  "password": "hello7!"
}


###
GET http://localhost:3000/groups/ac70388e-d87a-400c-ba2e-26ef5560ffc3/records/da1d7fa6-1475-4db8-8548-ea332c27f544

###
GET http://localhost:3000/ranking/monthly