###
POST  http://localhost:3000/group
Content-Type: application/json

{
  "name": "코드잇잇",
  "ownerNickName" : "3조",
  "description": "codiet.doe@example.com",
  "ownerPassword": "password123", 
  "goalRep" : 0,
  "discordURL": "dbxor@naver.com",
  "invitationURL": "1231351"
} 
 
###
PATCH http://localhost:3000/group/e5180cee-6701-4475-b15c-22e45851462e
Content-Type: application/json

{ 
  "ownerPassword": "password123",
  "goalRep" : 0,
  "discordURL": "dbtjd@naver.com",
  "invitationURL": "987654"
}

###
DELETE http://localhost:3000/group/cd43c115-6246-44af-b259-430848a26f3c
Content-Type: application/json

{
  "ownerPassword": "password123"
}
###
GET http://localhost:3000/group 
 
 

###
GET http://localhost:3000/group/f48ea255-1277-4c24-97a8-d767f7964718

 

###
PATCH http://localhost:3000/group/코드잇잇/likecount
Content-Type: application/json

{
  "likeCount": 1
} 
  
###
GET http://localhost:3000/group/코드잇/groupbadges
