###그룹 생성
POST http://localhost:8080/group/
Content-Type: application/json

{
  "name": "testGroup",
  "description": "group description",
  "photo": "http://example.com/photo.png",
  "goalRep": 10,
  "discordURL": "http://discordURL.com/invite/test",
  "invitationURL": "http://invitationURL.com/invite",
  "tags": ["tag1", "tag2"],
  "ownerNickname": "testUser",
  "ownerPassword": "password123"
}

### 그룹 수정
PATCH http://localhost:8080/group/bc626d75-c591-4ba8-8337-cd8177224f5e
Content-Type: application/json

{
  "ownerNickname": "testUser",
  "ownerPassword": "password123",
  "name": "Updated Group Name",
  "description": "Updated description",
  "photo": "http://example.com/newphoto.png",
  "goalRep": 20,
  "discordURL": "http://discordURL.com/newinvite",
  "invitationURL": "http://invitationURL.com/newinvite",
  "tags": ["newTag1", "newTag2"]
}
