export const GROUPS = [
  {
    name: '런닝 메이트',
    ownerNickname: 'speedster',
    ownerPassword: 'runfast123',
    description: '함께 달리며 건강을 챙기는 러닝 소모임!',
    photo: 'https://example.com/run.jpg',
    tags: ['러닝', '마라톤', '건강'],
    goalRep: 50,
    likeCount: 85,
    discordURL: 'https://discord.gg/runmate',
    invitationURL: 'https://invite.runmate.com',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    memberCount: 0,
  },
  {
    name: '헬스몬스터',
    ownerNickname: 'fitlife',
    ownerPassword: 'gymstrong123',
    description: '헬스를 사랑하는 모든 이들을 위한 모임!',
    photo: 'https://example.com/fitness.jpg',
    tags: ['헬스', '근력', '운동'],
    goalRep: 100,
    likeCount: 120,
    discordURL: 'https://discord.gg/healthmonster',
    invitationURL: 'https://invite.healthmonster.com',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    memberCount: 0,
  },
  {
    name: '사이클 챌린지',
    ownerNickname: 'cyclist_king',
    ownerPassword: 'cyclefast456',
    description: '자전거를 사랑하는 사람들의 모임!',
    photo: 'https://example.com/cycle.jpg',
    tags: ['사이클', '자전거', '경기'],
    goalRep: 200,
    likeCount: 150,
    discordURL: 'https://discord.gg/cyclechallenge',
    invitationURL: 'https://invite.cyclechallenge.com',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    memberCount: 0,
  },
  {
    name: '피트니스 애슬리트',
    ownerNickname: 'stronger',
    ownerPassword: 'trainhard789',
    description: '매일 훈련을 통해 더 강해지자!',
    photo: 'https://example.com/fitnessathlete.jpg',
    tags: ['피트니스', '운동', '챌린지'],
    goalRep: 150,
    likeCount: 200,
    discordURL: 'https://discord.gg/fitnessathlete',
    invitationURL: 'https://invite.fitnessathlete.com',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    memberCount: 0,
  },
  {
    name: '월드 챔피언',
    ownerNickname: 'championlife',
    ownerPassword: 'beachampion2023',
    description: '세계를 목표로 하는 최강의 운동 모임!',
    photo: 'https://example.com/worldchampion.jpg',
    tags: ['챔피언', '경쟁', '훈련'],
    goalRep: 500,
    likeCount: 250,
    discordURL: 'https://discord.gg/worldchampion',
    invitationURL: 'https://invite.worldchampion.com',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    memberCount: 0,
  },
];
