export const GROUPS = [
  {
    groupName: '런닝 메이트',
    nickName: 'speedster',
    password: 'runfast123',
    description: '함께 달리며 건강을 챙기는 러닝 소모임!',
    photo: 'https://example.com/run.jpg',
    tag: '러닝, 마라톤, 건강',
    goalCount: 50,
    recommendation: 85,
    discordURL: 'https://discord.gg/runmate',
    invitationURL: 'https://invite.runmate.com',
  },
  {
    groupName: '헬스몬스터',
    nickName: 'gymbeast',
    password: 'gymlover99',
    description: '근력 운동을 사랑하는 사람들의 모임!',
    photo: 'https://example.com/gym.jpg',
    tag: '헬스, 보디빌딩, 다이어트',
    goalCount: 30,
    recommendation: 90,
    discordURL: 'https://discord.gg/gymmonster',
    invitationURL: 'https://invite.gymmonster.com',
  },
  {
    groupName: '요가 힐링',
    nickName: 'yogalover',
    password: 'namaste123',
    description: '요가를 통해 몸과 마음의 평화를 찾는 모임',
    photo: 'https://example.com/yoga.jpg',
    tag: '요가, 명상, 힐링',
    goalCount: 20,
    recommendation: 78,
    discordURL: 'https://discord.gg/yogahealing',
    invitationURL: 'https://invite.yogahealing.com',
  },
  {
    groupName: '자전거 탐험대',
    nickName: 'bikerider',
    password: 'cyclelife',
    description: '자전거를 타고 전국을 누비는 라이딩 모임',
    photo: 'https://example.com/bike.jpg',
    tag: '자전거, 라이딩, 여행',
    goalCount: 100,
    recommendation: 88,
    discordURL: 'https://discord.gg/bikegroup',
    invitationURL: 'https://invite.bikegroup.com',
  },
  {
    groupName: '축구 사랑',
    nickName: 'soccerfan',
    password: 'goal123',
    description: '축구를 좋아하는 사람들이 모여서 함께 운동해요!',
    photo: 'https://example.com/soccer.jpg',
    tag: '축구, 풋살, 스포츠',
    goalCount: 40,
    recommendation: 92,
    discordURL: 'https://discord.gg/soccerlove',
    invitationURL: 'https://invite.soccerlove.com',
  },
  {
    groupName: '클라이밍 챌린지',
    nickName: 'rockclimber',
    password: 'climbhigh',
    description: '암벽 등반을 좋아하는 모험가들의 모임!',
    photo: 'https://example.com/climbing.jpg',
    tag: '클라이밍, 암벽등반, 챌린지',
    goalCount: 25,
    recommendation: 80,
    discordURL: 'https://discord.gg/climbingchallenge',
    invitationURL: 'https://invite.climbingchallenge.com',
  },
  {
    groupName: '수영 마스터',
    nickName: 'swimmerpro',
    password: 'divein',
    description: '수영을 배우고 함께 연습하는 소모임',
    photo: 'https://example.com/swim.jpg',
    tag: '수영, 운동, 다이어트',
    goalCount: 60,
    recommendation: 85,
    discordURL: 'https://discord.gg/swimmingmasters',
    invitationURL: 'https://invite.swimmingmasters.com',
  },
  {
    groupName: '배드민턴 클럽',
    nickName: 'shuttleking',
    password: 'smash123',
    description: '배드민턴을 좋아하는 사람들이 함께 치는 모임',
    photo: 'https://example.com/badminton.jpg',
    tag: '배드민턴, 스포츠, 건강',
    goalCount: 35,
    recommendation: 87,
    discordURL: 'https://discord.gg/badmintonclub',
    invitationURL: 'https://invite.badmintonclub.com',
  },
  {
    groupName: '등산 원정대',
    nickName: 'mountainhiker',
    password: 'hikehigh',
    description: '산을 오르며 자연을 즐기는 등산 소모임',
    photo: 'https://example.com/hiking.jpg',
    tag: '등산, 자연, 트레킹',
    goalCount: 75,
    recommendation: 90,
    discordURL: 'https://discord.gg/hikingteam',
    invitationURL: 'https://invite.hikingteam.com',
  },
  {
    groupName: '테니스 챌린저',
    nickName: 'tennispro',
    password: 'ace123',
    description: '테니스를 함께 연습하며 실력을 키우는 모임',
    photo: 'https://example.com/tennis.jpg',
    tag: '테니스, 운동, 챌린지',
    goalCount: 45,
    recommendation: 88,
    discordURL: 'https://discord.gg/tennischallenge',
    invitationURL: 'https://invite.tennischallenge.com',
  },
];
