export const GROUPS = [
  {
    name: '런닝 메이트',
    ownerNickName: 'speedster',
    ownerPassword: 'runfast123',
    description: '함께 달리며 건강을 챙기는 러닝 소모임!',
    photo: 'https://example.com/run.jpg',
    tags: ['러닝', '마라톤', '건강'],
    goalRep: 50,
    likeCount: 85,
    discordURL: 'https://discord.gg/runmate',
    invitationURL: 'https://invite.runmate.com',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    memberCount: 0,
  },
  {
    name: '헬스몬스터',
    ownerNickName: 'gymbeast',
    ownerPassword: 'gymlover99',
    description: '근력 운동을 사랑하는 사람들의 모임!',
    photo: 'https://example.com/gym.jpg',
    tags: ['헬스', '보디빌딩', '다이어트'],
    goalRep: 30,
    likeCount: 90,
    discordURL: 'https://discord.gg/gymmonster',
    invitationURL: 'https://invite.gymmonster.com',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    memberCount: 0,
  },
  {
    name: '요가 힐링',
    ownerNickName: 'yogalover',
    ownerPassword: 'namaste123',
    description: '요가를 통해 몸과 마음의 평화를 찾는 모임',
    photo: 'https://example.com/yoga.jpg',
    tags: ['요가', '명상', '힐링'],
    goalRep: 20,
    likeCount: 78,
    discordURL: 'https://discord.gg/yogahealing',
    invitationURL: 'https://invite.yogahealing.com',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    memberCount: 0,
  },
  {
    name: '자전거 탐험대',
    ownerNickName: 'bikerider',
    ownerPassword: 'cyclelife',
    description: '자전거를 타고 전국을 누비는 라이딩 모임',
    photo: 'https://example.com/bike.jpg',
    tags: ['자전거', '라이딩', '여행'],
    goalRep: 100,
    likeCount: 88,
    discordURL: 'https://discord.gg/bikegroup',
    invitationURL: 'https://invite.bikegroup.com',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    memberCount: 0,
  },
  {
    name: '축구 사랑',
    ownerNickName: 'soccerfan',
    ownerPassword: 'goal123',
    description: '축구를 좋아하는 사람들이 모여서 함께 운동해요!',
    photo: 'https://example.com/soccer.jpg',
    tags: ['축구', '풋살', '스포츠'],
    goalRep: 40,
    likeCount: 92,
    discordURL: 'https://discord.gg/soccerlove',
    invitationURL: 'https://invite.soccerlove.com',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    memberCount: 0,
  },
  {
    name: '클라이밍 챌린지',
    ownerNickName: 'rockclimber',
    ownerPassword: 'climbhigh',
    description: '암벽 등반을 좋아하는 모험가들의 모임!',
    photo: 'https://example.com/climbing.jpg',
    tags: ['클라이밍', '암벽등반', '챌린지'],
    goalRep: 25,
    likeCount: 80,
    discordURL: 'https://discord.gg/climbingchallenge',
    invitationURL: 'https://invite.climbingchallenge.com',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    memberCount: 0,
  },
  {
    name: '수영 마스터',
    ownerNickName: 'swimmerpro',
    ownerPassword: 'divein',
    description: '수영을 배우고 함께 연습하는 소모임',
    photo: 'https://example.com/swim.jpg',
    tags: ['수영', '운동', '다이어트'],
    goalRep: 60,
    likeCount: 85,
    discordURL: 'https://discord.gg/swimmingmasters',
    invitationURL: 'https://invite.swimmingmasters.com',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    memberCount: 0,
  },
  {
    name: '배드민턴 클럽',
    ownerNickName: 'shuttleking',
    ownerPassword: 'smash123',
    description: '배드민턴을 좋아하는 사람들이 함께 치는 모임',
    photo: 'https://example.com/badminton.jpg',
    tags: ['배드민턴', '스포츠', '건강'],
    goalRep: 35,
    likeCount: 87,
    discordURL: 'https://discord.gg/badmintonclub',
    invitationURL: 'https://invite.badmintonclub.com',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    memberCount: 0,
  },
  {
    name: '등산 원정대',
    ownerNickName: 'mountainhiker',
    ownerPassword: 'hikehigh',
    description: '산을 오르며 자연을 즐기는 등산 소모임',
    photo: 'https://example.com/hiking.jpg',
    tags: ['등산', '자연', '트레킹'],
    goalRep: 75,
    likeCount: 90,
    discordURL: 'https://discord.gg/hikingteam',
    invitationURL: 'https://invite.hikingteam.com',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    memberCount: 0,
  },
  {
    name: '테니스 챌린저',
    ownerNickName: 'tennispro',
    ownerPassword: 'ace123',
    description: '테니스를 함께 연습하며 실력을 키우는 모임',
    photo: 'https://example.com/tennis.jpg',
    tags: ['테니스', '운동', '챌린지'],
    goalRep: 45,
    likeCount: 88,
    discordURL: 'https://discord.gg/tennischallenge',
    invitationURL: 'https://invite.tennischallenge.com',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    memberCount: 0,
  },
];
